[package]
name = "bellman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4"
bit-vec = "0.4.4"
pairing = "0.14"
byteorder = "1"
bellman = "0.1.0"